.PHONY: clean All

All:
	@echo "----------Building project:[ EtherTerm - Debug ]----------"
	@"$(MAKE)" -f  "EtherTerm.mk" PreBuild && "$(MAKE)" -f  "EtherTerm.mk"
clean:
	@echo "----------Cleaning project:[ EtherTerm - Debug ]----------"
	@"$(MAKE)" -f  "EtherTerm.mk" clean
