.PHONY: clean All

All:
	@echo "----------Building project:[ EtherTerm - Debug ]----------"
	@"$(MAKE)" -f  "EtherTerm.mk" && "$(MAKE)" -f  "EtherTerm.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ EtherTerm - Debug ]----------"
	@"$(MAKE)" -f  "EtherTerm.mk" clean
